#test against this verison of Node.js
environment:
  matrix:
    #node.js
    - nodejs_verison: "6"

#Install scripts.(run after repo cloning)
install:
  #get the latest version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  #install modules
  - npm install

#post-install test scripts
test_script:
  #Output useful info for debugging
  - node --version
  - npm --version
  #run tests
  - npm test

#Dont actually build
build: off

